sustaining_keyboard_options = ['accordion', 'alto sax', 'bagpipe', 'bassoon', 
                               'brass section', 'choir aahs', 'cello', 
                               'church organ', 'clarinet', 'drawbar organ', 
                               'english horn', 'fiddle', 'flute', 'french horn', 
                               'harmonica', 'muted trumpet', 'oboe', 'ocarina', 
                               'pan flute', 'percussive organ', 'piccolo', 
                               'recorder', 'reed organ', 'rock organ', 
                               'shakuhachi', 'shanai', 'soprano sax', 
                               'string ensemble 1', 'string ensemble 2', 
                               'synth voice', 'synthbrass 1', 'synthbrass 2', 
                               'synthstrings 1', 'synthstrings 2', 'tenor sax', 
                               'trombone', 'trumpet', 'tuba', 'viola', 'violin', 
                               'voice oohs']

perc_keyboard_options = ['electric bass (finger)', 'electric guitar (jazz)', 
                         'celesta', 'electric piano 2', 'electric piano 1', 
                         'pizzicato strings', 'harpsichord', 
                         'electric guitar (muted)', 'synth bass 2', 'marimba', 
                         'koto', 'dulcimer', 'bright acoustic', 'glockenspiel', 
                         'acoustic guitar (nylon)', 'music box', 'melodic tom', 
                         'electric grand', 'acoustic bass', 'clav', 
                         'electric guitar (clean)', 'distorted guitar', 
                         'tubular bells', 'electric bass (pick)', 'sitar', 
                         'kalimba', 'synth bass 1', 'vibraphone', 'slap bass 1', 
                         'slap bass 2', 'acoustic grand', 'xylophone', 
                         'overdriven guitar', 'acoustic guitar (steel)', 
                         'banjo', 'shamisen', 'steel drums', 'fretless bass', 
                         'honky-tonk']

melody_keyboard_options = ['baritone sax', 'bagpipe', 'electric bass (finger)', 
                           'rock organ', 'electric guitar (jazz)', 'trombone', 
                           'brass section', 'celesta', 'tenor sax', 
                           'english horn', 'electric piano 2', 'clarinet', 
                           'electric piano 1', 'alto sax', 'violin', 
                           'pizzicato strings', 'accordion', 'harpsichord', 
                           'electric guitar (muted)', 'synth bass 2', 'marimba', 
                           'oboe', 'shakuhachi', 'string ensemble 1', 'koto', 
                           'reed organ', 'french horn', 'bright acoustic', 
                           'glockenspiel', 'acoustic guitar (nylon)', 
                           'church organ', 'electric grand', 'contrabass', 
                           'cello', 'acoustic bass', 'clav', 
                           'electric guitar (clean)','distorted guitar', 
                           'orchestral strings', 'concertina', 'synthstrings 2', 
                           'piccolo', 'synthstrings 1', 'electric bass (pick)', 
                           'sitar', 'synth bass 1', 'vibraphone', 'slap bass 1',
                           'trumpet', 'voice oohs', 'drawbar organ', 
                           'pan flute', 'acoustic grand', 'bassoon', 
                           'choir aahs', 'overdriven guitar', 'ocarina', 
                           'percussive organ', 'shanai', 
                           'acoustic guitar (steel)', 'viola', 
                           'string ensemble 2', 'fiddle', 'recorder', 'banjo', 
                           'flute', 'synthbrass 1', 'synthbrass 2', 
                           'synth voice', 'shamisen', 'soprano sax', 
                           'muted trumpet', 'harmonica', 'fretless bass', 
                           'honky-tonk', 'tuba']

bass_keyboard_options = ['baritone sax', 'bagpipe', 'electric bass (finger)', 
                         'rock organ', 'electric guitar (jazz)', 'trombone', 
                         'brass section', 'english horn', 'electric piano 2', 
                         'clarinet', 'electric piano 1', 'pizzicato strings', 
                         'accordion','harpsichord', 'electric guitar (muted)',
                         'synth bass 2', 'marimba', 'oboe', 'shakuhachi', 
                         'string ensemble 1', 'koto', 'reed organ', 
                         'french horn', 'bright acoustic',
                         'acoustic guitar (nylon)', 'church organ', 
                         'electric grand', 'contrabass', 'cello', 
                         'acoustic bass', 'clav', 'electric guitar (clean)', 
                         'concertina', 'synthstrings 2', 'piccolo', 
                         'synthstrings 1', 'electric bass (pick)', 'sitar', 
                         'kalimba', 'synth bass 1', 'vibraphone', 'slap bass 1', 
                         'slap bass 2', 'trumpet', 'voice oohs', 
                         'drawbar organ', 'pan flute', 'acoustic grand', 
                         'bassoon', 'choir aahs', 'ocarina', 'percussive organ', 
                         'shanai', 'acoustic guitar (steel)', 'viola', 
                         'string ensemble 2', 'fiddle', 'recorder', 'banjo',  
                         'flute', 'synthbrass 1', 'synthbrass 2', 'synth voice', 
                         'shamisen', 'soprano sax', 'muted trumpet', 
                         'blown bottle', 'harmonica', 'steel drums', 
                         'fretless bass', 'honky-tonk', 'tuba']